name: temp-bzip2-1.0.6
description: BZip 1.0.6
deps: []
action: build
src_uri: http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
md5: 00b516f4704d4a7cb50a1d97e6e8e15b
dir_name: bzip2-1.0.6
custom_install_command: make PREFIX=/tools install
preconfigure_commands:
  - |
    cat > ../../src/bzip2-1.0.6/configure << "EOF"
    #!/bin/bash
    echo "dummy configure script!"
    EOF
    chmod +x ../../src/bzip2-1.0.6/configure
  - cp -r ../../src/bzip2-1.0.6/* .
