name: temp-texinfo-6.3
description: GNU Texinfo 6.3
deps: []
action: build
src_uri: http://ftp.gnu.org/gnu/texinfo/texinfo-6.3.tar.xz
md5: 32baefe5c7080dfb512a4eac5ce67b2a
dir_name: texinfo-6.3
config_opts: --prefix=/tools
preinstall_commands:
 - make check
