name: temp-vkfs-prepare
description: 6.2. Preparing Virtual Kernel File Systems
deps: []
action: custom_commands
commands:
  - mkdir -pv $LFS/{dev,proc,sys,run}
  - sudo mknod -m 600 $LFS/dev/console c 5 1
  - sudo mknod -m 666 $LFS/dev/null c 1 3
