name: temp-strip-bins
description: Strips the tools directory of cruft (not working)
deps: []
action: custom_commands
commands:
 - strip --strip-debug /tools/lib/*
 - /usr/bin/strip --strip-unneeded /tools/{,s}bin/*
 - rm -rf /tools/{,share}/{info,man,doc}
